version: '3'
networks:
  exam:
    driver: bridge

services:

    #PHP Service
  app:
    build:
      context: ./
    image: exam/php
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - 6001:6001
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - exam

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-8000}:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - exam

  #MySQL Service
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: exam
      MYSQL_ROOT_PASSWORD: password
      
    volumes:
      - './mysqldata:/var/lib/mysql'
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - exam

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3309
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 3000M
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - exam
